name: Generate GitHub Contribution Graph Artwork

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate contribution graph SVG
        uses: jasineri/gitartwork@v1
        with:
          user_name: pro-bandey  
          text: PRO BANDEY         

      - name: Commit SVG
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update gitartwork.svg"
          file_pattern: gitartwork.svg
